In [1]:
import numpy as np

<h1>creating a numpy array</h1>

<h2>basic ndarray</h2>

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([1,2,0,3,4])

array([1, 2, 0, 3, 4])

<h2>array of zeros</h2>

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros(5,dtype=np.int32)

array([0, 0, 0, 0, 0])

 <h2>array of ones</h2>

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

<h2>random number in ndarray</h2>

In [12]:
np.random.rand(2,3)
#gives random values in between 0 and 1 with 2 rows and 3 columns

array([[0.82321547, 0.35859742, 0.30782639],
       [0.93874395, 0.35921542, 0.25950353]])

<h2>array of your choice</h2>

In [13]:
np.full((2,2),7)
#gives an array filling it with 7

array([[7, 7],
       [7, 7]])

In [14]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

<h2>Imatrix in numpy</h2>

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3,k=1)
#k is diagonal place
#positive is upper diagonal and negative is lower diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [18]:
np.eye(3,order='C')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<h2>evenly spaced ndarray</h2>

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [22]:
np.arange(5,dtype=np.float32)

array([0., 1., 2., 3., 4.], dtype=float32)

<h2>some basic problems</h2>

In [23]:
#sum of array
a=np.array([1,3,5,2])
sum(a)

11

In [24]:
#max
a=np.array([1,3,5,2])
max(a)

5

In [25]:
#find remainder of array multiplication divided by n
a=np.array([[5,3],[2,4]])
b=np.array([[3,5],[2,5]])
c=a*b
n=int(input("enter a number"))
c%n

enter a number2


array([[1, 1],
       [0, 0]], dtype=int32)

In [26]:
#interchange 1st and last elements
l=[1,43,6,3,2]
temp=l[0]
l[0]=l[-1]
l[-1]=temp
l

[2, 43, 6, 3, 1]

In [27]:
#swap any 2 function
l=[1,43,6,3,2]
a=int(input('enter an index'))

b=int(input('enter second index'))
temp=l[a]
l[a]=l[b]
l[b]=temp
l

enter an index1
enter second index2


[1, 6, 43, 3, 2]

In [28]:
#length of list
l=[1,43,6,3,2]
len(l)

5

<h2> Shape and Reshape </h2>

<h3> a)Dimensions of numpy array </h3>

In [29]:
a=np.array([[5,10,15],[20,25,30]])
print('Array:','\n',a)
print('Array:','\n',a.ndim)

Array: 
 [[ 5 10 15]
 [20 25 30]]
Array: 
 2


<h3> b)Shape of numpy array </h3>

In [30]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print('Array:','\n',a)
print('Array:','\n',a.shape)

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Array: 
 (2, 4)


In [31]:
print('Array:','\n',a.shape[0])

Array: 
 2


In [32]:
print('Array:','\n',a.shape[1])

Array: 
 4


<h3> c)size of the numpy array </h3>

In [33]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print('Array:','\n',a)
print('Array:','\n',a.size)

Array: 
 [[1 2 3 4]
 [5 6 7 8]]
Array: 
 8


In [34]:
print('manually determination of size of the array:',a.shape[0]*a.shape[1])

manually determination of size of the array: 8


<h3> d)reshaping of the numpy array </h3>

In [35]:
a=np.array([1,2,3,4])
np.reshape(a,(2,2))

array([[1, 2],
       [3, 4]])

In [36]:
a=np.array([1,2,3,4,5,6])
print('3rows:','\n',np.reshape(a,(3,-1)))

3rows: 
 [[1 2]
 [3 4]
 [5 6]]


In [37]:
a=np.array([1,2,3,4,5,6])
print('3columns:','\n',np.reshape(a,(-1,3)))

3columns: 
 [[1 2 3]
 [4 5 6]]


<h3> e)Flattening a numpy array </h3>

In [38]:
a=np.ones((2,2))
b=a.flatten()
c=a.ravel()
print('Original shape:',a.shape)
print('Array:','\n',a)
print('Shape after flatten:',b.shape)
print('Array:','\n',b)
print('shape after ravel:',c.shape)
print('Array:','\n',c)

Original shape: (2, 2)
Array: 
 [[1. 1.]
 [1. 1.]]
Shape after flatten: (4,)
Array: 
 [1. 1. 1. 1.]
shape after ravel: (4,)
Array: 
 [1. 1. 1. 1.]


<h3> f)Transpose of a numpy array </h3>

In [39]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.transpose(a)
print('Original:','\n','shape',a.shape,'\n',a)
print('Expend along columns:','\n','shape',b.shape,'\n',b)

Original: 
 shape (2, 4) 
 [[1 2 3 4]
 [5 6 7 8]]
Expend along columns: 
 shape (4, 2) 
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


<h2> Indexing and Slicing of Numpy Array </h2>

<h3> a)Slicing of 1d-numpy array

In [40]:
a=np.array([1,2,3,4,5,6])
print(a[1:5:2])

[2 4]


In [41]:
a=np.array([1,2,3,4,5,6])
print(a[1:6:2])

[2 4 6]


In [42]:
#missing the starting values
print(a[:6:2])

[1 3 5]


In [43]:
#missing the ending values
print(a[1::2])

[2 4 6]


In [44]:
#missing the step values
print(a[1:6:])

[2 3 4 5 6]


<h3> b)Slicing 2d-numpy array </h3>

In [45]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a[0,0])

1


In [46]:
print(a[1,2])

7


In [47]:
print(a[1,0])

5


In [48]:
print('First row values:','\n',a[0:1:])

First row values: 
 [[1 2 3 4]]


In [49]:
print('Alternative values from First row:','\n',a[0:1,::2])

Alternative values from First row: 
 [[1 3]]


In [50]:
print('Second column values:','\n',a[:,1::2])

Second column values: 
 [[2 4]
 [6 8]]


In [51]:
print('Arbtitary values:','\n',a[0:1,1:3])

Arbtitary values: 
 [[2 3]]


<h2>Slicing 3d-numpy array<h2/>

In [52]:
a=np.array([[[1,2],[3,4],[5,6]],
            [[7,8],[9,10],[11,12]],
            [[13,14],[15,16],[17,18]]])
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [53]:
print('First Array,First Row,First Columns:','\n',a[0,0,0])

First Array,First Row,First Columns: 
 1


In [54]:
print('First Array Last column:','\n',a[0,:,1])

First Array Last column: 
 [2 4 6]


In [55]:
print('First two rows for second & third array:','\n',a[1:,0:2,0:2])

First two rows for second & third array: 
 [[[ 7  8]
  [ 9 10]]

 [[13 14]
  [15 16]]]


<h2>Negative slicing of numpy arrays<h2/>

In [56]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[:,-1])

[ 5 10]


In [57]:
print(a[:,-1:-3:-1])

[[ 5  4]
 [10  9]]


In [58]:
print('original:','\n',a)

original: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
print('reverse:','\n',a[::-1,::-1])

reverse: 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


<h2>using flip() function</h2>

In [60]:
print('reverse array vertically:','\n',np.flip(a,axis=1))

reverse array vertically: 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]


In [61]:
print('reverse array horizontally:','\n',np.flip(a,axis=0))

reverse array horizontally: 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]
